#!/bin/bash

# Install a JupyterLab extension
jupyter labextension install @ijmbarr/jupyterlab_spellchecker

# gatk installation
#wget https://github.com/broadinstitute/gatk/releases/download/4.1.0.0/gatk-4.1.0.0.zip
#unzip gatk-4.1.0.0.zip
